# Generated by Django 3.0.8 on 2021-11-28 21:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("slack_id", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MenuOfTheDay",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FoodDish",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(max_length=140)),
                (
                    "menu_of_the_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_dishes",
                        to="menu_of_the_day.MenuOfTheDay",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeMenuSelection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "food_dish_customization",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="menu_of_the_day.Employee",
                    ),
                ),
                (
                    "menu_of_the_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="menu_of_the_day.MenuOfTheDay",
                    ),
                ),
                (
                    "selected_food_dish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="menu_of_the_day.FoodDish",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "menu_of_the_day")},
            },
        ),
    ]
